S3_BUCKETS:
  cds-54-phs000178:
    cred: "fence_bot"
    region: "us-east-1"
  cds-207-phs001787:
    cred: "fence_bot"
    region: "us-east-1"
  cds-211-phs001713:
    cred: "fence_bot"
    region: "us-east-1"
  cds-223-phs001926:
    cred: "fence_bot"
    region: "us-east-1"
  cds-225-phs001859:
    cred: "fence_bot"
    region: "us-east-1"
  cds-227-phs002011:
    cred: "fence_bot"
    region: "us-east-1"
  cds-229-phs001905:
    cred: "fence_bot"
    region: "us-east-1"
  cds-233-phs002050:
    cred: "fence_bot"
    region: "us-east-1"
  cds-234-phs002366:
    cred: "fence_bot"
    region: "us-east-1"
  cds-235-phs002250:
    cred: "fence_bot"
    region: "us-east-1"
  cds-237-phs001819:
    cred: "fence_bot"
    region: "us-east-1"
  cds-238-phs001524:
    cred: "fence_bot"
    region: "us-east-1"
  cds-243-phs002371:
    cred: "fence_bot"
    region: "us-east-1"
  cds-246-phs002517-imagingfiles-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-246-phs002517-sequencefiles-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-247-phs002518-sequencefiles-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-252-phs002529-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-252-phs002529-sequencefiles-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-252-phs002529-v1-p1-sequencefiles-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-253-phs002620-sequencefiles-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-253-phs002620.v1.p1-sequencefiles-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-254-phs002599:
    cred: "fence_bot"
    region: "us-east-1"
  cds-254-phs002599.v1.p1:
    cred: "fence_bot"
    region: "us-east-1"
  cds-255-phs002430-sequencefiles-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-256-phs002504-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-256-phs002504-sequencefiles-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-256-phs002504.v1.p1-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-256-phs002504.v1.p1-sequencefiles-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-257-phs002432:
    cred: "fence_bot"
    region: "us-east-1"
  cds-257-phs002432.v1.p1:
    cred: "fence_bot"
    region: "us-east-1"
  cds-258-phs002479:
    cred: "fence_bot"
    region: "us-east-1"
  cds-259-phs002293:
    cred: "fence_bot"
    region: "us-east-1"
  cds-260-phs002790-ccdi-ctsmc:
    cred: "fence_bot"
    region: "us-east-1"
  cds-260-phs002790-sequencefiles-ccdi-ctsmc:
    cred: "fence_bot"
    region: "us-east-1"
  cds-262-phs002431-sequencefiles-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-266-phs002677-p30-fy20:
    cred: "fence_bot"
    region: "us-east-1"
  cds-290-htan-x6gj-xr09:
    cred: "fence_bot"
    region: "us-east-1"
  cds-295-phs003155:
    cred: "fence_bot"
    region: "us-east-1"
  cds-296-phs001287:
    cred: "fence_bot"
    region: "us-east-1"
  cds-305-phs002790-production-ccdi-ctsmc:
    cred: "fence_bot"
    region: "us-east-1"
  cds-327-phs003111-mskcc:
    cred: "fence_bot"
    region: "us-east-1"
  cds-359-phs001327-ccss:
    cred: "fence_bot"
    region: "us-east-1"
  cds-371-phs003215-pdx:
    cred: "fence_bot"
    region: "us-east-1"
  cds-381-phs003143-mypart:
    cred: "fence_bot"
    region: "us-east-1"
  cds-412-phs001437-pptc:
    cred: "fence_bot"
    region: "us-east-1"
  cds-427-phs003432:
    cred: "fence_bot"
    region: "us-east-1"
  cds-447-target-c3dc:
    cred: "fence_bot"
    region: "us-east-1"
  cds-450-phs003519:
    cred: "fence_bot"
    region: "us-east-1"
  cds-474-phs003164-pivot-ccia:
    cred: "fence_bot"
    region: "us-east-1"
  cds-489-phs003622-chla:
    cred: "fence_bot"
    region: "us-east-1"
  cds-507-phs000720-rms:
    cred: "fence_bot"
    region: "us-east-1"
  cds-515-phs003163-pivot-chop:
    cred: "fence_bot"
    region: "us-east-1"
  cds-563-phs002883-production-ccdi-pedmatch:
    cred: "fence_bot"
    region: "us-east-1"
  cds-568-phs003161-pivot-msk:
    cred: "fence_bot"
    region: "us-east-1"  
  cgci-htmcp-dlbcl-phs000235-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  dcfprod-data-bucket:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-beataml1-cohort-phs001657-2-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-beataml1-cohort-phs001657-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-beataml1.0-crenolanib-phs001628-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-beataml1.0-crenolanib-phs001628-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-ccle-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-ccle-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cddp-eagle-1-phs001239-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cddp-eagle-1-phs001239-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cgci-blgsp-phs000235-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cgci-blgsp-phs000235-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cgci-phs000235-2-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cgci-phs000235-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cmi-asc-phs001931-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cmi-asc-phs001931-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cmi-mbc-phs001709-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cmi-mbc-phs001709-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cmi-mpc-phs001939-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cmi-mpc-phs001939-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cptac-2-phs000892-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cptac-2-phs000892-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cptac-phs001287-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-cptac-phs001287-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-ctsp-phs001175-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-ctsp-phs001175-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-exceptional-responders-er-phs001145-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-exceptional-responders-er-phs001145-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-fm-ad-phs001179-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-fm-ad-phs001179-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-genie-phs001337-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-genie-phs001337-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-hcmi-cmdc-phs001486-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-hcmi-cmdc-phs001486-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-h-phs001888-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-h-phs001888-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-i-phs002181-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-i-phs002181-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-u-phs002179-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-u-phs002179-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-w-phs001948-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-w-phs001948-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-z1a-phs001973-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-z1a-phs001973-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-z1d-phs001859-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-z1d-phs001859-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-mmrf-commpass-phs000748-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-mmrf-commpass-phs000748-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-mp2prt-wt-phs001965-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-mp2prt-wt-phs001965-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-nciccr-phs001444-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-nciccr-phs001444-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-ohsu-cnl-phs001799-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-ohsu-cnl-phs001799-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-organoid-pancreatic-phs001611-2-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-organoid-pancreatic-phs001611-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-rebc-thyr-phs001134-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-rebc-thyr-phs001134-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-target-phs000218-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-tcga-phs000178-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-varepop-apollo-phs001374-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-varepop-apollo-phs001374-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-wcdt-mcrpc-phs001648-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-wcdt-mcrpc-phs001648-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  idc-open-data:
    cred: 'fence_bot'
    region: 'us-east-1'
  idc-open-data-cr:
    cred: 'fence_bot'
    region: 'us-east-1'
  idc-open-data-two:
    cred: 'fence_bot'
    region: 'us-east-1'
  iodc-cimac-abtc1603-phs0037531:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-etctn9204-phs003291:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-etctn10026-phs003292:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-etctn10026-phs003293:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-etctn10021-phs003294:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-etctn10021-phs003295:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-etctn10013-phs003296:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-etctn10021-phs003294:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-etctn10104-phs003414:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-hcrngu16257-phs003372:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-nctne4412-phs003450:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-nctns1609-phs003443:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-nihcc14c0059g-phs003455:
    cred: "fence_bot"
    region: "us-east-1"
  iodc-cimac-nctns1400i-phs003412:
    cred: "fence_bot"
    region: "us-east-1"
  nci-cbiit-caninedatacommons-file:
    cred: "fence_bot"
    region: "us-east-1"
  nci-crdc-data-bucket-prod:
    cred: "fence_bot"
    region: "us-east-1" 
  pdcdatastore:
    cred: "fence_bot"
    region: "us-east-1"
  sddp-phs001554:
    cred: "fence_bot"
    region: "us-east-1"
  target-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  tcga-2-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  tcga-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  tcga-protected-dcf-databucket-gen3:
    cred: "fence_bot"
    region: "us-east-1"
  tcga-public-dcf-databucket-gen3:
    cred: "fence_bot"
    region: "us-east-1"
  match-b-phs002028-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  match-n-phs002151-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  mp2prt-all-phs002005-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  cgci-htmcp-dlbcl-phs000235-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  match-b-phs002028-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  match-n-phs002151-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  mp2prt-all-phs002005-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  nci-cbiit-clinical-cmb-prod:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-r-phs002029-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-s1-phs002153-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-s2-phs002178-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-z1I-phs002058-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-r-phs002029-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-s1-phs002153-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-s2-phs002178-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-z1I-phs002058-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-c1-phs002177-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-p-phs002152-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-z1b-phs002180-2-open:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-c1-phs002177-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-p-phs002152-controlled:
    cred: "fence_bot"
    region: "us-east-1"
  gdc-match-z1b-phs002180-controlled:
    cred: "fence_bot"
    region: "us-east-1"
