S3_BUCKETS:
  nci-cbiit-caninedatacommons-file:
    cred: 'fence_bot'
    region: 'us-east-1'
  nci-cbiit-clinical-cmb-stage:
    cred: 'fence_bot'
    region: 'us-east-1'
  tcga-protected-dcf-databucket-gen3:
    cred: 'fence_bot'
  tcga-public-dcf-databucket-gen3:
    cred: 'fence_bot'
  pdcdatastore-controlled:
    cred: 'fence_bot'
    region: 'us-east-1'
  dev-testing-bucketfor-matchdata:
    cred: 'fence_bot'
    region: 'us-east-1'
  dcf-staging-data-bucket:
    cred: 'fence_bot'
    region: 'us-east-1'
  crdc-ita:
    cred: 'fence_bot'
    region: 'us-east-1'
  crdc-itb:
    cred: 'fence_bot'
    region: 'us-east-1'
