name: Auto Label
on:
  pull_request:
    types: [opened, push, synchronize]

jobs:
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: banyan/auto-label@1.2
        if: github.event.pull_request.head.repo.full_name == 'uc-cdis/cdis-manifest'
        env:
          GITHUB_TOKEN: "${{ contains(secrets, 'GEN3_RELEASE_GH_TOKEN') && secrets.GEN3_RELEASE_GH_TOKEN || 'ignore' }}"
          
